config/routes.rb
Rails.application.routes.draw do
  root 'characters#index'
  devise_for :users

    resources :characters do
      resources :moves do
        resources :comments
      end
    end
    resources :characters do
      resources :moves do
        get '/comment_votes' => 'comment_votes#create'
    end
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :moves
  has_many :users,
    through: :user_characters
  has_many :user_characters

  validates :db_name, presence: true
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  paginates_per 5
  belongs_to :user
  belongs_to :move
  has_many :comment_votes

  validates :rating, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 1..5, message: " must be between 1 to 5" }
  validates :body, presence: true
  validates :body, length: { minimum: 5 }

def upvotes_score
  upvotes = comment_votes.where(upvote: 1).count
  if upvotes.nil?
    return 0
  else
    return upvotes
  end
end

def downvotes_score
  downvotes = comment_votes.where(downvote: 1).count
  if downvotes.nil?
    return 0
  else
    return downvotes
  end
end

def score
  self.upvotes_score - self.downvotes_score
end
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user

  validates :user, uniqueness: { scope: :comment }
  validates :upvote, presence: true
  validates :downvote, presence: true
  validates :upvote, numericality: { only_integer: true }
  validates :downvote, numericality: { only_integer: true }
  # between 1 and 0

  def destroy_if_exists(vote_type)
    if vote_type == "upvote"
      if self.upvote == 1
        self.destroy
        return nil
      else
        self
      end
    else
      if self.downvote == 1
        self.destroy
        return nil
      else
        self
      end
    end
  end

  def change_vote(vote_type)
    if vote_type == "upvote"
      self.upvote = 1
      self.downvote = 0
    elsif vote_type == "downvote"
      self.downvote = 1
      self.upvote = 0
    end
  end
end

app/models/frame.rb
class Frame < ActiveRecord::Base
  belongs_to :move

  validates :startup, presence: true
  validates :active, presence: true
  validates :recover, presence: true
  validates :blockadv, presence: true
  validates :hitadv, presence: true
  validates :cancelwindow, presence: true
end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :character
  has_many :comments
  has_many :move_votes
  has_many :users,
    through: :user_moves
  has_many :user_moves
  has_many :frames

  validates :db_name, presence: true
  validates :name, presence: true
  validates :button_command, presence: true
  validates :move_type, presence: true
  validates :damage, presence: true
  validates :character_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters,
    through: :user_characters
  has_many :user_characters
  has_many :moves,
    through: :user_moves
  has_many :user_moves
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/models/user_character.rb
class UserCharacter < ActiveRecord::Base
  belongs_to :user
  belongs_to :character
end

app/models/user_move.rb
class UserMove < ActiveRecord::Base
  belongs_to :user
  belongs_to :move
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all.order('name ASC')
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    character_params['name']
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character
      flash[:success] = 'A New Challenger Appears'
    else
      flash[:errors] = @character.errors.full_messages.join(". ")
      render :new
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    flash[:success] = "Character Deleted"
    redirect_to "/"
  end

  private

  def character_params
    params.require(:character).permit(:name, :db_name, :description)
  end

end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController

  def new
    @character = Character.find(params[:character_id])
    @move = @character.moves.find(params[:move_id])
    @comment = Comment.find(params[:id])
    @vote = Vote.new(comment_id: params[:comment_id],user_id: current_user.id)
  end

  def create
    @character = Character.find(params[:character_id])
    @move = @character.moves.find(params[:move_id])
    @comment = @move.comments.where(id: params[:comment_id])
    vote_check = CommentVote.find_by(comment_id: params[:comment_id],
                              user_id: current_user)

    if vote_check.nil?
      @comment_vote = CommentVote.new(comment_id: params[:comment_id], user_id: current_user.id)
    else
      @comment_vote = vote_check.destroy_if_exists(params[:vote_type])
    end

    if !@comment_vote.nil?
      @comment_vote.change_vote(params[:vote_type])
      @comment_vote.save
    end

    respond_to do |format|
      check_comment = Comment.find(params[:comment_id])
      format.html
      format.json { render json: check_comment.score }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::Helpers::DateHelper
  def new
    @character = Character.find(params[:character_id])
    @move = @character.moves.find(params[:move_id])
    @comment = Comment.new
  end

  def create
    @character = Character.find(params[:character_id])
    @move = @character.moves.find(params[:move_id])
    @comment = Comment.new(comment_params)
    @comment.move_id = @move.id
    @comment.user = current_user
    if @comment.save
      time_text = time_ago_in_words(@comment.created_at)
      render json: {
        rating: @comment.rating,
        body: @comment.body,
        user: @comment.user.email,
        timeText: time_text
      }
    else
      flash[:errors] = @comment.errors.full_messages.join(". ")
      redirect_to character_move_path(@character.id, @move.id)
    end
  end

  def destroy
    @character = Character.find(params[:character_id])
    @move = @character.moves.find(params[:move_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = "Comment Deleted!"
    redirect_to character_move_path(@character.id, @move.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:rating, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  def show
    @character = Character.find(params[:character_id])
    @move = @character.moves.find(params[:id])
    @comments = @move.comments.order('created_at DESC').page params[:page]
    @comment = Comment.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def background_image(image='')
    if image.empty?
      "the-index-page"
    else
      image
    end
  end
end

app/views/characters/index.html.erb
<head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<br>

  <div style="display:flex;justify-content:center;align-items:center;">
    <div class="panel">
      <h1 style="text-shadow: 2px 2px black">Select A Character</h1>
    </div>
  </div>

  <div class = "row index_row">
    <div class = "small-6  medium-8 small-centered large-11 column">
      <ul class = "small-block-grid-1 medium-block-grid-3 large-block-grid-5 panelz" >
        <% @characters.each do |character| %>
            <li>
              <div class="panel">
                  <div class="index-name">
                    <h3 style="text-shadow: 2px 2px black">
                      <%= link_to character.name, character_path(character), :style => "color: #ead61c;" %>
                    </h3>
                  </div>
                  <div style="display:flex;justify-content:center;align-items:center;">
                    <div id="char-icon"><%= link_to (image_tag("character_icons/#{character.name}-Icon.png")), character_path(character), :class =>"hvr-bounce-in" %></div>
                  </div>
              </div>
            </li>
        <% end %>
      </ul>

      <% if current_user %>
        <% if current_user.admin %>
          <%= link_to "Add Character (Admins Only)", new_character_path,
           class: "button success hvr-bounce-in" %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/characters/new.html.erb
<div class="row">
  <h1>Add a New Character</h1>
</div>

 <%= form_for @character do |f| %>
  <div class= "row">
    <div class= "field columns small-6">
      <%= f.label :name, :style => "color: #ead61c;" %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class= "row">
    <div class= "field columns small-6">
      <%= f.label :db_name, :style => "color: #ead61c;" %>
      (the name that is passed into the database to
      retrieve related image files. Must contain no
      spaces; use hyphens instead)
      <%= f.text_field :db_name %>
    </div>
  </div>
  <br>
  <div class= "row">
    <div class= "field columns small-8">
  <%= f.label :description, :style => "color: #ead61c;" %>
  <%= f.text_area :description %>
    </div>
  </div>
  <br>
    <div class= "row">
  <%= f.submit "Add Character", class: "success button" %>
    </div>
 <% end %>
    <div class= "row">
<%= link_to "Back to home", root_path, class: "button" %>
  </div>

app/views/characters/show.html.erb
<% provide(:background, @character.db_name) %>
<head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<br>
<div style="display:flex;justify-content:center;align-items:center;">
  <div class="panelzz">
    <div class="panel" style="text-shadow: 2px 2px black">
      <h1><%=@character.name %></h1>
      <%=@character.description %>
    </div>
  </div>
</div>

<div class="move-properties">

  <% @character.moves.each do |m| %>
    <div class="row fullWidth">
      <div class="small-12 medium-4 columns">
        <div class="row">
          <table class="panelzz" style="margin-top: 4.5em;text-shadow: 2px 2px black">
            <tr>
              <td><h3 class="text-center"><%= link_to m.name, character_move_path(@character.id, m.id), :class =>"hvr-bounce-in" %></h3></td>
              <td><h3 class="text-center"><%= m.button_command %></h3></td>
            </tr>
            <tr>
              <td><h3 class="text-center">Move Type: <%= m.move_type %></h3></td>
              <td><h3 class="text-center">Damage: <%= m.damage  %></h3></td>
            </tr>
          </table>
        </div>
      </div>


      <% f = m.frames.first %>
      <div class="small-12 medium-4 columns">
        <div class="row">
          <table class="panelzz" style="text-shadow: 2px 2px black">
            <tr>
              <td><p><h3 class="text-center">Startup: <%= f.startup %></h3></p></td>
              <td><p><h3 class="text-center">Active:  <%= f.active %></h3></p></td>
            </tr>
            <tr>
              <td><p><h3 class="text-center">Recover:  <%= f.recover %></h3></p></td>
              <td><p><h3 class="text-center">Block Adv:  <%= f.blockadv  %></h3></p></td>
            </tr>
            <tr>
              <td><p><h3 class="text-center">Hit Adv:  <%= f.hitadv  %></h3></p></td>
              <td><p><h3 class="text-center">Cancel Window:  <%= f.cancelwindow  %></h3></p></td>
            </tr>
          </table>
        </div>
      </div>
        <%= video_tag(["https://s3.amazonaws.com/alot/mkx-clips/#{m.db_name}.mp4"], :size => "380x300", :controls => true, :id => "move-video", :style => "display: block;margin: 0 auto;") %>
    </div>
  <% end %>
</div>



<% if current_user %>
  <% if current_user.admin %>
    <%= link_to "Delete Character (Admins Only)", @character, method: :delete,
     class: "button alert hvr-bounce-in" %>
  <% end %>
<% end %>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mortal Frames</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= background_image(yield(:background)) %>">

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h4><a href="/"> Mortal Frames</a><li class="divider"></li></h4>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul align="right", style="display: block;float: right;margin: 0 auto;">
        <%- if current_user -%>
          <li class="divider"></li>
          <li id="register-button-2"><%= link_to current_user.email, edit_user_registration_path(current_user) %></li>
          <li class="divider"></li>
          <li id="register-button"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li class="divider"></li>
        <%- else -%>
          <li class="divider"></li>
          <li id="register-button"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="divider"></li>
          <li id="register-button-2"><%= link_to 'Sign In', new_user_session_path %></li>
          <li class="divider"></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
  <div data-alert class="alert-box info radius" tabindex="0" aria-live="assertive" role="alertdialog">
      <%= value %>
  <button tabindex="0" class="close" aria-label="Close Alert">&times;</button>
  </div>

  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/moves/show.html.erb
<% provide(:background, @character.db_name) %>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<div style="display:flex;align-items:left;">
  <%= link_to character_path(@character), :class =>"hvr-bounce-in" do %>
    <i class="fa fa-arrow-circle-left fa-2x" style="padding-top: 10px;padding-left: 6px;color: yellow;"></i>
  <% end %>
</div>
<div style="display:flex;justify-content:center;align-items:center;">
  <div class="panelzz">
    <div class="panel">
      <h1 style="text-shadow: 2px 2px black"><%=@move.name %></h1>
    </div>
  </div>
</div>
<%= video_tag(["https://s3.amazonaws.com/alot/mkx-clips/#{@move.db_name}.mp4"], :controls => true, :id => "move-video-big") %>

<div style="display:flex;justify-content:center;align-items:center;">
  <div class="panel">
    <h2 style="text-shadow: 2px 2px black"`>Comments</h2>
  </div>
</div>

<%- if current_user -%>
  <div class="new-comment">
    <button data-remote="true" class="button radius button-new-form mall-6 large-10 large-offset-1">
    Submit Your Comment</button>
    <div class="hide comment-form">
      <div class="panelz">
        <div class="panel">
          <p style="text-shadow: 2px 2px black">NEW COMMENT</p>
          <%= form_for [@character, @move, @comment], :id => 'comment-form' do |f| %>
            <div class= "row">
              <div class= "field columns small-12 large-12">
                <div class="field">
                  <%= f.label :body, :style => "color: #ead61c;text-shadow: 2px 2px black" %>
                  <%= f.text_area :body, :id => 'comment-body' %>
                </div>
              </div>
            </div>
            <div class= "row">
              <div class= "field columns small-8 large-8">
                <div class="field">
                  <%= f.label :rating, :style => "color: #ead61c;text-shadow: 2px 2px black" %>
                  <%= f.select :rating, options_from_collection_for_select([1, 2, 3, 4, 5], "to_s", "to_s"), :id => 'comment_rating' %>
                </div>
              </div>
            </div>
      <%= f.submit "Submit Comment", class: "success button", id: "submitting_comment" %>
        </div>
      </div>
     <% end %>
    </div>
  </div>

  <%- else -%>
    <span class="small-6 large-10 large-offset-1">
      <%= link_to 'Submit Your Comment', new_user_session_path,
      class: "button radius" %>
    </span>
  <%- end -%>

  <div class="comments-container">
      <% @comments.each do |c| %>
      <div class="panelz" style="padding-bottom:10px;">
        <div class="panel small-6 large-10 large-offset-1" style="display:block;", id="comments_panel">
      <p style="text-shadow: 2px 2px black">Written <%= time_ago_in_words(c.created_at) %> ago by <%= c.user.try(:email)%>.</p>
        <div class="panel", id="comments">

          <% if current_user %>
            <div id="<%= c.id %>">
              <div id="ballotBox" style="float:left;">
                <a id="upvote" class="vote"> <%= image_tag("upvote.png", :class =>"hvr-grow") %> </a>
                <div id="comment_score" style="padding-left:18px;"> <%= c.score %> </div>
                <a id="downvote" class="vote"><%= image_tag("downvote.png", :class =>"hvr-grow") %></a>
              </div>
            </div>
            <% else %>
            <div id="ballotBox" style="float:left;">
              <a> <%= link_to image_tag("upvote.png"), new_user_session_path,:id =>"novoteforyou", :class =>"hvr-grow" %> </a>
              <div id="comment_score" style="padding-left:18px;"> <%= c.score %> </div>
              <a> <%= link_to image_tag("downvote.png"), new_user_session_path, :id =>"novoteforyou2", :class =>"hvr-grow"  %></a>
            </div>
            <% end %>

        <p>
          <h5 style="text-shadow: 2px 2px black;", id="c-rating">Rating: <%= c.rating %></h5>
        </p>
        <p>
          <h2 style="text-shadow: 2px 2px black", id="c-body"><%= c.body %></h2>
        </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>

      <div class="small-6 large-10 large-offset-1" id ="paginator">
        <%= paginate @comments %>
      </div>